# Generated by Django 5.2.6 on 2025-09-14 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpassword',
            name='email',
            field=models.EmailField(max_length=50, unique=True),
        ),
    ]
