# Generated by Django 5.2.6 on 2025-09-14 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_userpassword_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpassword',
            name='email',
        ),
    ]
